### ISSUE TITLE
Change import path

### ISSUE THREAD

**Issue by arthur-e** [pegler/pytzwhere#12]
Presumably, `tzNameAt` is the business end of this module. In order to use it, it must be imported and invoked this way:

```
from tzwhere import tzwhere
tzwhere.tzwhere.tzNameAt(...)
```

Or:
```
from tzwhere.tzwhere import *
tzwhere.tzNameAt(...)
```

Any thoughts on removing the extraneous `tzwhere` parts? e.g.
```
import tzwhere
tzwhere.tzNameAt(...)
```

**Comment by cstich** [comment]
If we change this, this breaks the API. This won't happen. If you are annoyed by the typing, try something like this:

    from tzwhere import tzwhere
    tz = tzwhere.tzwhere()
    tz.tzNameAt(35.29, -89.66)
