### ISSUE TITLE
Update source file and add attribution for the original data

### ISSUE THREAD

**Issue by cstich** [pegler/pytzwhere#20]
There seems to have been an update of the original [data](http://efele.net/maps/tz/world/) since this package was originally built.

Also add attribution for the guy who built the map in the first place.

**Comment by pegler** [comment]
I honestly don't remember where I got the data. I originally just wrote a strict port of the node.js code. Attributing the data source in addition to the original author would be great.

Also, shoot me an email. My username at gmail.com.

**Comment by cstich** [comment]
This is done.
