### ISSUE TITLE
Pickle the shapely polygons

### ISSUE THREAD

**Issue by cstich** [pegler/pytzwhere#23]
If we pickle the shapely polygons, then we could speed up the import probably quite considerably. Potential downside: This might not work if you have a shapely/python mismatch somewhere.

**Comment by cstich** [comment]
The plan is to create this on install, so that it plays nicely with all potential versions of installed libraries.

**Comment by pegler** [comment]
I'm sure setup tools supports this somehow.  Sounds like a nice optimization
