### ISSUE TITLE
'module' object has no attribute 'tzwhere'

### ISSUE THREAD

**Issue by ImanYZ** [pegler/pytzwhere#24]
Dear Sir/Madam,

I installed pytzwhere via:

pip install git+https://github.com/pegler/pytzwhere.git

"import tzwhere" works, but "tz = tzwhere.tzwhere()" returns the following error message:

AttributeError: 'module' object has no attribute 'tzwhere'

Thank you so much for your time and concern.
Best regards,
Iman

**Comment by cstich** [comment]
You are importing the module tzwhere and not the class.  And I should fix the documentation.
Try something like

    from tzwhere import tzwhere

should work

**Comment by ImanYZ** [comment]
@cstich, Thank you so much.

**Comment by cstich** [comment]
You are welcome :)

**Comment by ImanYZ** [comment]
By the way, this package is awesome. It took a while for me to find it, but it is exactly what I wanted.

Actually I have a list of city and state or country names and I was trying to identify their current time.
For this purpose, I combined the following four libraries:

from pytz import timezone
from geopy import geocoders
from tzwhere import tzwhere
from pytz import timezone

and the following is an example of my code:

location = "Sackville, Canada"
g = geocoders.GoogleV3()
place, (lat, lng) = g.geocode(location)
tz = tzwhere.tzwhere()
timeZoneObj = tz.tzNameAt(lat, lng)
now_time = datetime.now(timezone(timeZoneObj))

print now_time => 2015-06-26 15:56:37.425000-03:00

Do you know any more efficient way for this purpose?

Thank you again,
Iman

**Comment by cstich** [comment]
Thank you.

As you are already effectively queering Google, you could just try queering Google for the timezone directly. Have a look at [their API](https://developers.google.com/maps/documentation/timezone/) and see whether that fits your requirements.

Alternatively there is also a database of cities and their timezone - [cities timezone](http://www.citytimezones.info/index.htm) - but I am not sure how complete the list is.

**Comment by ImanYZ** [comment]
I am actually using Google Geocoder API in order to locate the coordinates of addresses, cities, states, or countries. I think this is important, because these addresses are not formatted appropriately. Some of them may include only country name and others might include city and state. After having the coordinates, it's not efficient for me to use Google Time Zone API, because it doubles the number of requests that my program sends to Google APIs using the same key, which might exceed my quota.

**Comment by cstich** [comment]
That makes sense and the code you posted looks very reasonable to me.

The only way and from the top of my head to speed up your code would be to parallize it. That should be pretty straightforward.

**Comment by cstich** [comment]
@ImanYZ this comment is just to make sure you see my edited answer from just a second ago. I am not sure how github handles edits and notifications. Better be safe than sorry.

**Comment by ImanYZ** [comment]
@cstich, Thank you so much for your comment.
