### ISSUE TITLE
PyPI package out of date

### ISSUE THREAD

**Issue by jtbates** [pegler/pytzwhere#25]
The tzwhere PyPI package is over a year old and is not Python 3 compatible.  Could a new release be made with the current updates?

**Comment by pegler** [comment]
I just uploaded version 2.0 to pypi.  Thanks for the ping

**Comment by jtbates** [comment]
That was quick! Thanks @pegler!

**Comment by jtbates** [comment]
Also - the package can now be added to the 'Programming Language :: Python :: 3' category
