### ISSUE TITLE
Configure Coveralls and TravisCI

### ISSUE THREAD

**Issue by pegler** [pegler/pytzwhere#7]

**Comment by cstich** [comment]
@pegler It looks like only [admins](http://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator) can add projects to TravisCI. 

Could you possibly do that? I already set up the config script (I am not a 100% sure it works yet though)

**Comment by pegler** [comment]
Done.  I added the badge to the readme which triggered the first build: https://travis-ci.org/pegler/pytzwhere/builds/67418759

**Comment by cstich** [comment]
Thank you :)

**Comment by pegler** [comment]
converalls can be configured via .travis.yml I believe

**Comment by cstich** [comment]
I think so, yes. I will have a look.
