### ISSUE TITLE
Remove unnecessary data files

### ISSUE THREAD

**Issue by pegler** [pegler/pytzwhere#9]
currently the package has a lot of data files that aren't necessary.  The most compact one should be used and the rest deleted.  It will most likely be the pickle version.  If so, a utility command to parse a geojson file and write a pickle file should be added

**Comment by cstich** [comment]
I think it makes the most sense to default to the CSV file. It seems to be faster, smaller and use less memory. I will pencil this in (in one of the next iterations).
